---
title: "Enron_Email_Network"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(knitr)
library(igraphdata)
library(igraph)
library(network)

data(enron)
```

```{r}
##
# preprocess the role for the dataset aka preprocess the nodes
##
enron <- enron - V(enron)[V(enron)$Note == "NA"]

process_position <- function(p){
  if(grepl("CEO", p)){
    return("CEO")
  }
  if(grepl("Director", p)){
    return("Director")
  }
  if(grepl("Vice President", p)){
    return("Vice President")
  }
  if(grepl("President", p)){
    return("President")
  }
  if(grepl("Trader", p)){
    return("Trader")
  }
  if(grepl("Lawyer", p)){
    return("Lawyer")
  }
  if(grepl("Manager", p)){
    return("Manager")
  }
  if(grepl("Employee", p)){
    return("Employee")
  }
  return("Other")
}

V(enron)$role <- sapply(V(enron)$Note, process_position)
```

```{r}
##
# preprocess the edges of the dataset to only keep relevant data about 
# the enron scandel 
##

# 16 indicates the downfall of the company
enron <- enron - E(enron)[E(enron)$LDC_topic != 16 & E(enron)$LDC_topic != 4]
#enron <- enron - E(enron)[E(enron)$LDC_topic > 8 | E(enron)$LDC_topic < 1]
##
# Preprocess the nodes to assign level to each of node
##
process_level <- function(p){
  if(grepl("CEO", p)){
    return(5)
  }
  if(grepl("Vice President", p)){
    return(3)
  }
  if(grepl("President", p)){
    return(4)
  }
  if(grepl("Trader", p)){
    return(1)
  }
  if(grepl("Director", p)){
    return(2)
  }
  if(grepl("Lawyer", p)){
    return(1)
  }
  if(grepl("Manager", p)){
    return(1)
  }
  if(grepl("Employee", p)){
    return(0)
  }
  return(0)
}
V(enron)$level <- sapply(V(enron)$role, process_level)

# assign each employee a binary status as either a manager or not
V(enron)$manager <- !(V(enron)$role %in% c("Employee", "Trader", "Other"))
V(enron)$manager[49] <- TRUE # noticed an error with not assigning Enron individual Jeff Dasovich (a director with the highest degree in the network) as a manager rather than an employee in the dataset

# construct an adjacency matrix
enron.adj = as.matrix(as_adjacency_matrix(enron))

# get the indegree and outdegree of each node
# or the number of emails send out and number of emails receive
in.deg = colSums(enron.adj)
out.deg = rowSums(enron.adj)
```

## EDA

# Basic Descriptives
```{r}

```

# Descriptives Related to Research Question
```{r}
in.deg.man = in.deg[V(enron)$manager]
in.deg.emp = in.deg[!V(enron)$manager]
out.deg.man = out.deg[V(enron)$manager]
out.deg.emp = out.deg[!V(enron)$manager]

# average indegree for manager
mean(in.deg.man)
# average indegree for employee
mean(in.deg.emp)

# average indegree for manager
mean(out.deg.man)
# average indegree for employee
mean(out.deg.emp)
```

```{r}
cor(out.deg, V(enron)$level)
cor(in.deg, V(enron)$level)
```
Base on the positive correlations between the level of the employees and both out degree and in degree, we can tell that higher level emoloyees send and receive more emails. The stronger correlation betweein in degree and level indicates that they a more significant amount of emails.

```{r}
# outdegree and year
plot(V(enron)$level, out.deg, main="out-degree vs level in firm", pch=20)
abline(lm(out.deg ~ V(enron)$level), col="red")

# indegree and year
plot(V(enron)$level, in.deg, main="in-degree vs level in firm", pch=20)
abline(lm(in.deg ~ V(enron)$level), col="red")
```

```{r}

```


